server:
  port: 8086

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cs-user-profile-api
  
  datasource:
    url: jdbc:mysql://localhost:3306/csdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: examly
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
