server:
  port: 8082

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cs-currency-exchange-api

api:
  client:
    ratesApiUrl: http://cs-currency-rates-api
    transactionApiUrl: http://cs-transaction-api

# resilience4j:
#   retry:
#    instances:
#       apiGatewayRetry:
#         max-attempts: 3
#         wait-duration: 5s
