server:
  port: 8080

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cs-api-gateway
  cloud:
    gateway:
      routes:
        - id: cs-currency-exchange-api
          uri: lb://cs-currency-exchange-api
          predicates:
            - Path=/api/cs/currency-exchange/**
          filters:
            - RewritePath=/api/cs/currency-exchange/(?<ResourcePath>.*), /api/currency-exchange/$\{ResourcePath}

        - id: cs-currency-rates-api
          uri: lb://cs-currency-rates-api
          predicates:
            - Path=/api/cs/currency-rates/**
          filters:
            - RewritePath=/api/cs/currency-rates/(?<ResourcePath>.*), /api/currency-rates/$\{ResourcePath}

        - id: cs-auth-api
          uri: lb://cs-auth-api
          predicates:
            - Path=/api/cs/auth/**
          filters:
            - RewritePath=/api/cs/auth/(?<ResourcePath>.*), /api/auth/$\{ResourcePath}

        - id: cs-user-profile-api
          uri: lb://cs-user-profile-api
          predicates:
            - Path=/api/cs/user-profile/**
          filters:
            - RewritePath=/api/cs/user-profile/(?<ResourcePath>.*), /api/user-profile/$\{ResourcePath}

        - id: cs-transaction-api
          uri: lb://cs-transaction-api
          predicates:
            - Path=/api/cs/exchange-transactions/**
          filters:
            - RewritePath=/api/cs/exchange-transactions/(?<ResourcePath>.*), /api/exchange-transactions/$\{ResourcePath}

        - id: cs-logger-api
          uri: lb://cs-logger-api
          predicates:
            - Path=/api/cs/logger/**
          filters:
            - RewritePath=/api/cs/logger/(?<ResourcePath>.*), /api/logger/$\{ResourcePath}
